language: node_js
node_js: node
cache: npm
install:
  - npm ci
script:
  - echo REACT_APP_TMDB_API_KEY=$TMDB_API_KEY > .env
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
